experimentName: xgboost_tuning
trialConcurrency: 15
maxTrialNumber: 3600
trainingService:
  platform: local
searchSpaceFile: search_space.json
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trialCommand: python3 train_nni.py --filepath output/dataforxgboost_a.csv --target_column VisitDuration --exp_dir nni6_explog --groupingparams groupingsetting.yml
trialCodeDirectory: .
experimentWorkingDirectory: nni6_explog