experimentName: xgboost_tuning
trialConcurrency: 15
maxTrialNumber: 3600
trainingService:
  platform: local
searchSpaceFile: search_space.json
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trialCommand: python3 train_nni.py --filepath output/dataforxgboost.csv --target_column VisitDuration --exp_dir nni1_explog --groupingparams grouping_params.yml
trialCodeDirectory: .
experimentWorkingDirectory: nni1_explog